version: '3.1'
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      inside-airbnb:
        ipv4_address: 172.21.0.2
    expose:
      - "5432"

  api-abnb:
    # image: caidam/api-abnb 
    build: .
    container_name: api-abnb
    volumes:
      - ./:/app # Sync local directory with container
    ports:
      - "5000:80"
      - "8443:443"
    depends_on:
      - postgres-db
    networks:
      inside-airbnb:
        ipv4_address: 172.21.0.3

networks:
  inside-airbnb:
    ipam:
      config:
        - subnet: 172.21.0.0/16